new-vagrant/sistemabase/config/routes.rb
Rails.application.routes.draw do
  #get 'contacto/index'
  get 'contacto' => "contacto#index"

  get 'suscripcion/index'
  
  #get 'tienda/index'
  get 'tienda' => "tienda#index"
  #get 'aprende/index'
  get 'aprende' => "aprende#index"
  #get 'terapiahorticola/index'
  get 'terapiahorticola' => "terapiahorticola#index"
  #get 'impacto/index'
  get 'impacto' => "impacto#index"

  resources :venta
  resources :categoria
  resources :productos
  resources :clientes
  #inicio
  get '' => "welcome#index"
  #users
  get "users" => "users#show"
  post "users/new" => "users#create"


  #login y session
  get "login" => "sessions#new"
  post "sessions/new/user" => "sessions#user_create"
  delete "sessions/destroy/user" => "sessions#user_destroy"

  delete '/logins/destroy' =>"sessions#destroy" , as: "logout"

end

new-vagrant/sistemabase/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

new-vagrant/sistemabase/app/models/categorium.rb
class Categorium < ApplicationRecord
    has_many :producto
end

new-vagrant/sistemabase/app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :venta
end

new-vagrant/sistemabase/app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :categoria
end

new-vagrant/sistemabase/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #relaciones

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, uniqueness: true, format: { with: EMAIL_REGEX }
  validates :password, length: {minimum: 8, maximum: 72}, on: :create
  validates :nombre, :apellido, :email, presence: true
  validates :nombre, :apellido, length: {minimum: 2}
  before_save :downcase_email

  private
  def downcase_email
    self.email.downcase!
  end
end

new-vagrant/sistemabase/app/models/venta.rb
class Venta < ApplicationRecord
    belongs_to :cliente
end

new-vagrant/sistemabase/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido, :email, :contraseña)
    end
end

new-vagrant/sistemabase/app/controllers/tienda_controller.rb
class TiendaController < ApplicationController
  def index
  end
end

new-vagrant/sistemabase/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "registro"
  before_action :require_login, only: [:show]
  def index
  end
  def create
    @user = User.new(parametros_user)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User creado exitosamente "
      redirect_to users_path
    else
      flash[:errors] = [@user.errors.full_messages]
      redirect_to '/' #retorno al welcome#index con errores
    end
  end
  def show
    @user = User.find_by(id: session[:user_id])
  end
  def require_login
    if session[:user_id] == nil
      redirect_to '/'
    end
  end
  def parametros_user
    params.require(:user).permit(:nombre, :apellido, :email, :password)
  end
end

new-vagrant/sistemabase/app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: %i[ show edit update destroy ]

  # GET /venta or /venta.json
  def index
    @venta = Ventum.all
  end

  # GET /venta/1 or /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @ventum = Ventum.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta or /venta.json
  def create
    @ventum = Ventum.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, notice: "Ventum was successfully created." }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1 or /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: "Ventum was successfully updated." }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1 or /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url, notice: "Ventum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ventum_params
      params.require(:ventum).permit(:fecha, :cliente, :descuento, :monto, :cantidad)
    end
end

new-vagrant/sistemabase/app/helpers/application_helper.rb
module ApplicationHelper
end

new-vagrant/sistemabase/app/helpers/aprende_helper.rb
module AprendeHelper
end

new-vagrant/sistemabase/app/helpers/categoria_helper.rb
module CategoriaHelper
end

new-vagrant/sistemabase/app/helpers/clientes_helper.rb
module ClientesHelper
end

new-vagrant/sistemabase/app/helpers/contacto_helper.rb
module ContactoHelper
end

new-vagrant/sistemabase/app/helpers/impacto_helper.rb
module ImpactoHelper
end

new-vagrant/sistemabase/app/helpers/productos_helper.rb
module ProductosHelper
end

new-vagrant/sistemabase/app/helpers/sessions_helper.rb
module SessionsHelper
end

new-vagrant/sistemabase/app/helpers/suscripcion_helper.rb
module SuscripcionHelper
end

new-vagrant/sistemabase/app/helpers/tienda_helper.rb
module TiendaHelper
end

new-vagrant/sistemabase/app/helpers/users_helper.rb
module UsersHelper
end

new-vagrant/sistemabase/app/helpers/venta_helper.rb
module VentaHelper
end

new-vagrant/sistemabase/app/helpers/welcome_helper.rb
module WelcomeHelper
end

new-vagrant/sistemabase/app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_field :contraseña %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

new-vagrant/sistemabase/app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

new-vagrant/sistemabase/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Contraseña</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.contraseña %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

new-vagrant/sistemabase/app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

new-vagrant/sistemabase/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Contraseña:</strong>
  <%= @cliente.contraseña %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>