new-vagrant/sistemabase/config/routes.rb
Rails.application.routes.draw do
  #get 'contacto/index'
  get 'contacto' => "contacto#index"

  get 'suscripcion/index'
  
  #get 'tienda/index'
  get 'tienda' => "tienda#index"
  #get 'aprende/index'
  get 'aprende' => "aprende#index"
  #get 'terapiahorticola/index'
  get 'terapiahorticola' => "terapiahorticola#index"
  #get 'impacto/index'
  get 'impacto' => "impacto#index"

  resources :venta
  resources :categoria
  resources :productos
  resources :clientes
  #inicio
  get '' => "welcome#index"
  #users
  get "users" => "users#show"
  post "users/new" => "users#create"


  #login y session
  get "login" => "sessions#new"
  post "sessions/new/user" => "sessions#user_create"
  delete "sessions/destroy/user" => "sessions#user_destroy"

  delete '/logins/destroy' =>"sessions#destroy" , as: "logout"

end

new-vagrant/sistemabase/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

new-vagrant/sistemabase/app/models/categorium.rb
class Categorium < ApplicationRecord
    has_many :producto
end

new-vagrant/sistemabase/app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :venta
end

new-vagrant/sistemabase/app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :categoria
end

new-vagrant/sistemabase/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #relaciones

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, uniqueness: true, format: { with: EMAIL_REGEX }
  validates :password, length: {minimum: 8, maximum: 72}, on: :create
  validates :nombre, :apellido, :email, presence: true
  validates :nombre, :apellido, length: {minimum: 2}
  before_save :downcase_email

  private
  def downcase_email
    self.email.downcase!
  end
end

new-vagrant/sistemabase/app/models/venta.rb
class Venta < ApplicationRecord
    belongs_to :cliente
end

new-vagrant/sistemabase/app/controllers/admin/categoria_controller.rb
class Admin::CategoriaController < ApplicationController
end

new-vagrant/sistemabase/app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: "Categorium was successfully created." }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: "Categorium was successfully updated." }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: "Categorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorium_params
      params.require(:categorium).permit(:nombre, :descripcion)
    end
end

new-vagrant/sistemabase/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "registro"
  before_action :require_login, only: [:show]
  def index
  end
  def create
    @user = User.new(parametros_user)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User creado exitosamente "
      redirect_to users_path
    else
      flash[:errors] = [@user.errors.full_messages]
      redirect_to '/' #retorno al welcome#index con errores
    end
  end
  def show
    @user = User.find_by(id: session[:user_id])
  end
  def require_login
    if session[:user_id] == nil
      redirect_to '/'
    end
  end
  def parametros_user
    params.require(:user).permit(:nombre, :apellido, :email, :password)
  end
end

new-vagrant/sistemabase/app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: %i[ show edit update destroy ]

  # GET /venta or /venta.json
  def index
    @venta = Ventum.all
  end

  # GET /venta/1 or /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @ventum = Ventum.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta or /venta.json
  def create
    @ventum = Ventum.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, notice: "Ventum was successfully created." }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1 or /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: "Ventum was successfully updated." }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1 or /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url, notice: "Ventum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ventum_params
      params.require(:ventum).permit(:fecha, :cliente, :descuento, :monto, :cantidad)
    end
end

new-vagrant/sistemabase/app/helpers/admin/categoria_helper.rb
module Admin::CategoriaHelper
end

new-vagrant/sistemabase/app/helpers/application_helper.rb
module ApplicationHelper
end

new-vagrant/sistemabase/app/helpers/aprende_helper.rb
module AprendeHelper
end

new-vagrant/sistemabase/app/helpers/categoria_helper.rb
module CategoriaHelper
end

new-vagrant/sistemabase/app/helpers/clientes_helper.rb
module ClientesHelper
end

new-vagrant/sistemabase/app/helpers/contacto_helper.rb
module ContactoHelper
end

new-vagrant/sistemabase/app/helpers/impacto_helper.rb
module ImpactoHelper
end

new-vagrant/sistemabase/app/helpers/productos_helper.rb
module ProductosHelper
end

new-vagrant/sistemabase/app/helpers/sessions_helper.rb
module SessionsHelper
end

new-vagrant/sistemabase/app/helpers/suscripcion_helper.rb
module SuscripcionHelper
end

new-vagrant/sistemabase/app/helpers/tienda_helper.rb
module TiendaHelper
end

new-vagrant/sistemabase/app/helpers/users_helper.rb
module UsersHelper
end

new-vagrant/sistemabase/app/helpers/venta_helper.rb
module VentaHelper
end

new-vagrant/sistemabase/app/helpers/welcome_helper.rb
module WelcomeHelper
end

new-vagrant/sistemabase/app/views/categoria/_form.html.erb
<%= form_with(model: categorium) do |form| %>
  <% if categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
        <% categorium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

new-vagrant/sistemabase/app/views/categoria/edit.html.erb
<h1>Editing Categorium</h1>

<%= render 'form', categorium: @categorium %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

new-vagrant/sistemabase/app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoria</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.nombre %></td>
        <td><%= categorium.descripcion %></td>
        <td><%= link_to 'Show', categorium %></td>
        <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorium', new_categorium_path %>

new-vagrant/sistemabase/app/views/categoria/new.html.erb
<h1>New Categorium</h1>

<%= render 'form', categorium: @categorium %>

<%= link_to 'Back', categoria_path %>

new-vagrant/sistemabase/app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @categorium.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @categorium.descripcion %>
</p>

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>