new-vagrant/sistemabase/config/routes.rb
Rails.application.routes.draw do
  #get 'contacto/index'
  get 'contacto' => "contacto#index"

  get 'suscripcion/index'
  
  #get 'tienda/index'
  get 'tienda' => "tienda#index"
  #get 'aprende/index'
  get 'aprende' => "aprende#index"
  #get 'terapiahorticola/index'
  get 'terapiahorticola' => "terapiahorticola#index"
  #get 'impacto/index'
  get 'impacto' => "impacto#index"

  resources :venta
  resources :categoria
  resources :productos
  resources :clientes
  #inicio
  get '' => "welcome#index"
  #users
  get "users" => "users#show"
  post "users/new" => "users#create"


  #login y session
  get "login" => "sessions#new"
  post "sessions/new/user" => "sessions#user_create"
  delete "sessions/destroy/user" => "sessions#user_destroy"

  delete '/logins/destroy' =>"sessions#destroy" , as: "logout"

end

new-vagrant/sistemabase/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

new-vagrant/sistemabase/app/models/categorium.rb
class Categorium < ApplicationRecord
    has_many :producto
end

new-vagrant/sistemabase/app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :venta
end

new-vagrant/sistemabase/app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :categoria
end

new-vagrant/sistemabase/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #relaciones

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, uniqueness: true, format: { with: EMAIL_REGEX }
  validates :password, length: {minimum: 8, maximum: 72}, on: :create
  validates :nombre, :apellido, :email, presence: true
  validates :nombre, :apellido, length: {minimum: 2}
  before_save :downcase_email

  private
  def downcase_email
    self.email.downcase!
  end
end

new-vagrant/sistemabase/app/models/venta.rb
class Venta < ApplicationRecord
    belongs_to :cliente
end

new-vagrant/sistemabase/app/controllers/admin/productos_controller.rb
class Admin::ProductosController < ApplicationController
end

new-vagrant/sistemabase/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :descripción, :categoria, :valoración, :feeling)
    end
end

new-vagrant/sistemabase/app/controllers/tienda_controller.rb
class TiendaController < ApplicationController
  def index
  end
end

new-vagrant/sistemabase/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "registro"
  before_action :require_login, only: [:show]
  def index
  end
  def create
    @user = User.new(parametros_user)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User creado exitosamente "
      redirect_to users_path
    else
      flash[:errors] = [@user.errors.full_messages]
      redirect_to '/' #retorno al welcome#index con errores
    end
  end
  def show
    @user = User.find_by(id: session[:user_id])
  end
  def require_login
    if session[:user_id] == nil
      redirect_to '/'
    end
  end
  def parametros_user
    params.require(:user).permit(:nombre, :apellido, :email, :password)
  end
end

new-vagrant/sistemabase/app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: %i[ show edit update destroy ]

  # GET /venta or /venta.json
  def index
    @venta = Ventum.all
  end

  # GET /venta/1 or /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @ventum = Ventum.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta or /venta.json
  def create
    @ventum = Ventum.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, notice: "Ventum was successfully created." }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1 or /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: "Ventum was successfully updated." }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1 or /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url, notice: "Ventum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ventum_params
      params.require(:ventum).permit(:fecha, :cliente, :descuento, :monto, :cantidad)
    end
end

new-vagrant/sistemabase/app/helpers/admin/productos_helper.rb
module Admin::ProductosHelper
end

new-vagrant/sistemabase/app/helpers/application_helper.rb
module ApplicationHelper
end

new-vagrant/sistemabase/app/helpers/aprende_helper.rb
module AprendeHelper
end

new-vagrant/sistemabase/app/helpers/categoria_helper.rb
module CategoriaHelper
end

new-vagrant/sistemabase/app/helpers/clientes_helper.rb
module ClientesHelper
end

new-vagrant/sistemabase/app/helpers/contacto_helper.rb
module ContactoHelper
end

new-vagrant/sistemabase/app/helpers/impacto_helper.rb
module ImpactoHelper
end

new-vagrant/sistemabase/app/helpers/productos_helper.rb
module ProductosHelper
end

new-vagrant/sistemabase/app/helpers/sessions_helper.rb
module SessionsHelper
end

new-vagrant/sistemabase/app/helpers/suscripcion_helper.rb
module SuscripcionHelper
end

new-vagrant/sistemabase/app/helpers/tienda_helper.rb
module TiendaHelper
end

new-vagrant/sistemabase/app/helpers/users_helper.rb
module UsersHelper
end

new-vagrant/sistemabase/app/helpers/venta_helper.rb
module VentaHelper
end

new-vagrant/sistemabase/app/helpers/welcome_helper.rb
module WelcomeHelper
end

new-vagrant/sistemabase/app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripción %>
    <%= form.text_field :descripción %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :valoración %>
    <%= form.number_field :valoración %>
  </div>

  <div class="field">
    <%= form.label :feeling %>
    <%= form.number_field :feeling %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

new-vagrant/sistemabase/app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

new-vagrant/sistemabase/app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripción</th>
      <th>Categoria</th>
      <th>Valoración</th>
      <th>Feeling</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.descripción %></td>
        <td><%= producto.categoria %></td>
        <td><%= producto.valoración %></td>
        <td><%= producto.feeling %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

new-vagrant/sistemabase/app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

new-vagrant/sistemabase/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @producto.descripción %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria %>
</p>

<p>
  <strong>Valoración:</strong>
  <%= @producto.valoración %>
</p>

<p>
  <strong>Feeling:</strong>
  <%= @producto.feeling %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>